name: Test
on: push
jobs:
  default:
   runs-on: ${{ matrix.os }}
   strategy:
     matrix:
       os: [ubuntu-latest, windows-latest]
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Compose
       run: docker-compose up --detach
     - name: List containers
       run: docker ps -a
     - name: Cleanup
       run: docker-compose down
