name: Test
on: push
jobs:
  default:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Docker Compose
       run: docker compose up --detach
     - name: List containers
       run: docker ps -a
     - name: Cleanup
       run: docker compose down
